name: dvis_server
dependencies:
  - pip:
    -  flask==1.1.2
    - flask_socketio==4.3.0
    - numpy
    - pillow
    - trimesh
    - simple-websocket==0.2.0
    - python-socketio==4.6.1
    - eventlet
    - jinja2==3.0.2
    - itsdangerous==2.0.1
    - werkzeug==2.0.3
    - visdom